backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "landing-page"
    label: "Landing Page"
    folder: "content/landing-pages"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "landing-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Landing Page Sections"
        name: "sections"
        widget: "list"
        types:
          #JUMBOTRON
          - label: "Jumbotron"
            name: "jumbotron"
            widget: object
            fields:
              - { label: Header, name: header, widget: markdown }
              - {
                  label: Button Text,
                  name: buttonText,
                  widget: string,
                  required: false,
                }
              - {
                  label: Button Color,
                  name: buttonColor,
                  widget: string,
                  required: false,
                }
              - {
                  label: Button Link,
                  name: buttonLink,
                  widget: string,
                  required: false,
                }
              - { label: "Background Image", name: desktopImage, widget: image }
              - {
                  label: "Custom CSS",
                  name: customCSS,
                  widget: text,
                  required: false,
                }

          #FEATURES
          - label: "Features"
            name: "features"
            widget: object
            fields:
              - { label: Header, name: header, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: string,
                  required: false,
                }
              - {
                  label: Button Text,
                  name: buttonText,
                  widget: string,
                  required: false,
                }
              - {
                  label: Button Link,
                  name: buttonLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Background Color,
                  name: bgColor,
                  widget: string,
                  required: false,
                }
              - {
                  label: Numbered Features,
                  name: numberedFeatures,
                  widget: boolean,
                  default: false,
                }
              - {
                  label: Features Image Height,
                  name: imageHeight,
                  widget: string,
                  required: false,
                }
              - label: Features
                name: features
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - {
                      label: Title,
                      name: title,
                      widget: string,
                      required: false,
                    }
                  - {
                      label: Description,
                      name: description,
                      widget: string,
                      required: false,
                    }
          #GRID
          - label: "Grid"
            name: "grid"
            widget: object
            fields:
              - {
                  label: "Grid Size",
                  name: "gridSize",
                  widget: number,
                  valueType: int,
                  default: 2,
                }
              - {
                  label: "Large Screen Padding",
                  name: "lgPadding",
                  widget: string,
                  default: "",
                  required: false,
                }
              - {
                  label: "Medium Screen Padding",
                  name: "mdPadding",
                  widget: string,
                  default: "",
                  required: false,
                }
              - {
                  label: "Background Color",
                  name: "bgColor",
                  widget: string,
                  default: "#fff",
                  required: false,
                }

          #MARKDOWN
          - label: "Text Editor"
            name: "textEditor"
            widget: object
            fields:
              - { label: "Text Content", name: "textContent", widget: markdown }
              - {
                  label: "Custom CSS",
                  name: customCSS,
                  widget: text,
                  required: false,
                }

          #FORM MODAL
          - label: "Form Modal"
            name: "formModal"
            widget: object
            fields:
              - { label: "Header", name: "header", widget: string }
              - label: Form Fields
                name: "formFields"
                widget: "list"
                required: false
                fields:
                  - { label: ID, name: id, widget: string, required: false }
                  - { label: Name, name: name, widget: string, required: false }
                  - { label: Type, name: type, widget: string, required: false }
                  - {
                      label: Placeholder,
                      name: placeholder,
                      widget: string,
                      required: false,
                    }
                  - label: Options
                    name: options
                    widget: list
                    fields:
                      - label: Value
                        name: value
                        widget: string
                        required: false
              - {
                  label: "Custom CSS",
                  name: customCSS,
                  widget: text,
                  required: false,
                }
